#!/bin/sh
# Compatible with ash/busybox shell

#=================================================
#	System Required: OpenWrt 19.07+
#	Description: BBR TCP Acceleration Script for OpenWrt
#	Version: 1.0.0
#	Updated: 2024
#	Note: OpenWrt uses ash shell (BusyBox)
#=================================================

sh_ver="1.0.0"

# Color definitions (ANSI escape codes)
GREEN='\033[32m'
RED='\033[31m'
YELLOW='\033[33m'
BLUE='\033[34m'
GREEN_BG='\033[42;37m'
NC='\033[0m'

# Message prefixes
info() {
    echo -e "${GREEN}[信息]${NC} $1"
}

error() {
    echo -e "${RED}[错误]${NC} $1"
}

warning() {
    echo -e "${YELLOW}[注意]${NC} $1"
}

success() {
    echo -e "${GREEN}[成功]${NC} $1"
}

# Check if running as root
check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        error "此脚本必须以root权限运行！"
        exit 1
    fi
}

# Check if system is OpenWrt
check_openwrt() {
    if [ ! -f /etc/openwrt_release ]; then
        error "此脚本仅支持 OpenWrt 系统！"
        exit 1
    fi
    
    # Get OpenWrt version
    . /etc/openwrt_release
    DISTRIB_RELEASE="${DISTRIB_RELEASE:-unknown}"
    DISTRIB_DESCRIPTION="${DISTRIB_DESCRIPTION:-OpenWrt}"
    
    info "检测到 ${DISTRIB_DESCRIPTION}"
}

# Get kernel version
get_kernel_version() {
    kernel_version_full=$(uname -r)
    kernel_version=$(echo "$kernel_version_full" | cut -d'-' -f1)
    kernel_major=$(echo "$kernel_version" | cut -d'.' -f1)
    kernel_minor=$(echo "$kernel_version" | cut -d'.' -f2)
}

# Show kernel version
show_kernel_version() {
    get_kernel_version
    info "内核版本: ${GREEN}${kernel_version_full}${NC}"
}

# Check if BBR is available
check_bbr_available() {
    get_kernel_version
    
    # BBR requires kernel 4.9+
    if [ "$kernel_major" -lt 4 ] || { [ "$kernel_major" -eq 4 ] && [ "$kernel_minor" -lt 9 ]; }; then
        return 1
    fi
    
    # Check if BBR module is loaded or available
    if grep -q bbr /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null; then
        return 0
    fi
    
    # Try to load BBR module
    if insmod /lib/modules/$(uname -r)/tcp_bbr.ko 2>/dev/null; then
        return 0
    fi
    
    # Check if kmod-tcp-bbr is installed
    if [ -f /lib/modules/$(uname -r)/tcp_bbr.ko ]; then
        return 0
    fi
    
    return 1
}

# Check if BBR kernel module package is installed
check_bbr_package() {
    if opkg list-installed 2>/dev/null | grep -q "kmod-tcp-bbr"; then
        return 0
    fi
    return 1
}

# Install BBR kernel module package
install_bbr_package() {
    info "正在更新软件包列表..."
    opkg update
    
    info "正在安装 BBR 内核模块..."
    if opkg install kmod-tcp-bbr; then
        success "BBR 模块安装成功！"
        return 0
    else
        error "BBR 模块安装失败！"
        warning "可能是内核版本不支持或软件源问题"
        return 1
    fi
}

# Create sysctl configuration
create_sysctl_config() {
    local config_file="/etc/sysctl.d/12-tcp-bbr.conf"
    
    # Create sysctl.d directory if not exists
    if [ ! -d /etc/sysctl.d ]; then
        mkdir -p /etc/sysctl.d
    fi
    
    cat > "$config_file" << 'EOF'
# BBR TCP Congestion Control for OpenWrt
# Auto-generated by tcp_openwrt.sh

net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
EOF
    
    info "配置文件已创建: $config_file"
}

# Create optimized sysctl configuration
create_sysctl_config_optimized() {
    local config_file="/etc/sysctl.d/12-tcp-bbr.conf"
    
    # Create sysctl.d directory if not exists
    if [ ! -d /etc/sysctl.d ]; then
        mkdir -p /etc/sysctl.d
    fi
    
    cat > "$config_file" << 'EOF'
# BBR TCP Congestion Control for OpenWrt (Optimized)
# Auto-generated by tcp_openwrt.sh

# BBR core settings
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr

# BBR optimizations
net.ipv4.tcp_notsent_lowat=16384
net.ipv4.tcp_slow_start_after_idle=0

# Network buffer optimizations (adjusted for router)
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.core.rmem_default=65536
net.core.wmem_default=65536
net.ipv4.tcp_rmem=4096 65536 16777216
net.ipv4.tcp_wmem=4096 65536 16777216

# Connection handling
net.core.somaxconn=4096
net.core.netdev_max_backlog=4096
net.ipv4.tcp_max_syn_backlog=4096
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_fin_timeout=15

# Keepalive
net.ipv4.tcp_keepalive_time=600
net.ipv4.tcp_keepalive_intvl=30
net.ipv4.tcp_keepalive_probes=3

# MTU probing
net.ipv4.tcp_mtu_probing=1

# TCP Fast Open
net.ipv4.tcp_fastopen=3
EOF
    
    info "优化配置文件已创建: $config_file"
}

# Create module autoload configuration
create_module_config() {
    local module_file="/etc/modules.d/99-tcp-bbr"
    
    echo "tcp_bbr" > "$module_file"
    info "模块自动加载配置已创建: $module_file"
}

# Remove all configurations
remove_all() {
    info "正在清除所有 TCP 加速配置..."
    
    # Remove sysctl config
    if [ -f /etc/sysctl.d/12-tcp-bbr.conf ]; then
        rm -f /etc/sysctl.d/12-tcp-bbr.conf
        info "已删除 sysctl 配置"
    fi
    
    # Remove module autoload config
    if [ -f /etc/modules.d/99-tcp-bbr ]; then
        rm -f /etc/modules.d/99-tcp-bbr
        info "已删除模块自动加载配置"
    fi
    
    # Reset to default congestion control
    if [ -f /proc/sys/net/ipv4/tcp_congestion_control ]; then
        echo "cubic" > /proc/sys/net/ipv4/tcp_congestion_control 2>/dev/null
    fi
    
    # Apply default sysctl
    sysctl -p /etc/sysctl.conf 2>/dev/null
    
    success "清除完成"
}

# Apply sysctl settings
apply_sysctl() {
    info "正在应用 sysctl 配置..."
    
    # Load BBR module first
    if [ -f /lib/modules/$(uname -r)/tcp_bbr.ko ]; then
        insmod /lib/modules/$(uname -r)/tcp_bbr.ko 2>/dev/null
    fi
    
    # Apply all sysctl configurations
    if [ -d /etc/sysctl.d ]; then
        for conf in /etc/sysctl.d/*.conf; do
            if [ -f "$conf" ]; then
                sysctl -p "$conf" 2>/dev/null
            fi
        done
    fi
    
    # Also apply main sysctl.conf
    sysctl -p /etc/sysctl.conf 2>/dev/null
}

# Enable BBR
enable_bbr() {
    info "正在启用 BBR..."
    show_kernel_version
    
    # Check if BBR package is installed
    if ! check_bbr_package; then
        warning "未检测到 BBR 内核模块包"
        echo ""
        printf "是否要安装 kmod-tcp-bbr 包? [Y/n]: "
        read -r choice
        case "$choice" in
            n|N)
                error "取消安装，BBR 启用失败"
                return 1
                ;;
            *)
                if ! install_bbr_package; then
                    return 1
                fi
                ;;
        esac
    fi
    
    # Remove old config
    remove_all >/dev/null 2>&1
    
    # Create new config
    create_sysctl_config
    create_module_config
    
    # Apply settings
    apply_sysctl
    
    # Verify
    local current_cc
    current_cc=$(cat /proc/sys/net/ipv4/tcp_congestion_control 2>/dev/null)
    if [ "$current_cc" = "bbr" ]; then
        success "BBR 启动成功！"
        return 0
    else
        error "BBR 启动失败！当前算法: $current_cc"
        return 1
    fi
}

# Enable BBR with optimizations
enable_bbr_optimized() {
    info "正在启用 BBR (优化版)..."
    show_kernel_version
    
    # Check if BBR package is installed
    if ! check_bbr_package; then
        warning "未检测到 BBR 内核模块包"
        echo ""
        printf "是否要安装 kmod-tcp-bbr 包? [Y/n]: "
        read -r choice
        case "$choice" in
            n|N)
                error "取消安装，BBR 启用失败"
                return 1
                ;;
            *)
                if ! install_bbr_package; then
                    return 1
                fi
                ;;
        esac
    fi
    
    # Remove old config
    remove_all >/dev/null 2>&1
    
    # Create optimized config
    create_sysctl_config_optimized
    create_module_config
    
    # Apply settings
    apply_sysctl
    
    # Verify
    local current_cc
    current_cc=$(cat /proc/sys/net/ipv4/tcp_congestion_control 2>/dev/null)
    if [ "$current_cc" = "bbr" ]; then
        success "BBR (优化版) 启动成功！"
        return 0
    else
        error "BBR 启动失败！当前算法: $current_cc"
        return 1
    fi
}

# Enable SQM (Smart Queue Management) - OpenWrt specific
enable_sqm_info() {
    echo ""
    info "===== SQM 智能队列管理 ====="
    echo ""
    echo "SQM 是 OpenWrt 提供的高级流量整形工具，可以有效降低延迟。"
    echo ""
    echo "安装 SQM:"
    echo "  opkg update"
    echo "  opkg install luci-app-sqm"
    echo ""
    echo "配置建议:"
    echo "  1. 在 LuCI 界面: 网络 -> SQM QoS"
    echo "  2. 接口: 选择 WAN 接口"
    echo "  3. 下载/上传速度: 设置为实际带宽的 85-95%"
    echo "  4. 队列规则: cake (推荐) 或 fq_codel"
    echo "  5. 链路层: 根据实际连接类型选择"
    echo ""
    warning "SQM 和 BBR 可以同时使用，效果更佳"
    echo ""
}

# Check current status
check_status() {
    get_kernel_version
    
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║${NC}       ${GREEN}OpenWrt 系统状态检查${NC}            ${BLUE}║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
    
    # System info
    if [ -f /etc/openwrt_release ]; then
        . /etc/openwrt_release
        info "系统版本: ${GREEN}${DISTRIB_DESCRIPTION:-OpenWrt}${NC}"
    fi
    
    info "内核版本: ${GREEN}${kernel_version_full}${NC}"
    
    # Check BBR support
    if [ "$kernel_major" -ge 5 ] || { [ "$kernel_major" -eq 4 ] && [ "$kernel_minor" -ge 9 ]; }; then
        info "BBR 支持: ${GREEN}是 (内核 ${kernel_major}.${kernel_minor})${NC}"
    else
        info "BBR 支持: ${RED}否 (需要内核 4.9+)${NC}"
    fi
    
    # Check BBR package
    if check_bbr_package; then
        info "BBR 模块包: ${GREEN}已安装${NC} ✓"
    else
        info "BBR 模块包: ${YELLOW}未安装${NC}"
    fi
    
    # Current congestion control
    local current_cc
    current_cc=$(cat /proc/sys/net/ipv4/tcp_congestion_control 2>/dev/null)
    if [ -n "$current_cc" ]; then
        if [ "$current_cc" = "bbr" ]; then
            info "拥塞控制: ${GREEN}${current_cc}${NC} ✓"
        else
            info "拥塞控制: ${YELLOW}${current_cc}${NC}"
        fi
    else
        info "拥塞控制: ${RED}未知${NC}"
    fi
    
    # Current qdisc
    local current_qdisc
    current_qdisc=$(cat /proc/sys/net/core/default_qdisc 2>/dev/null)
    if [ -n "$current_qdisc" ]; then
        if [ "$current_qdisc" = "fq" ]; then
            info "队列算法: ${GREEN}${current_qdisc}${NC} ✓"
        else
            info "队列算法: ${YELLOW}${current_qdisc}${NC}"
        fi
    fi
    
    # Available congestion control algorithms
    local available_cc
    available_cc=$(cat /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null)
    if [ -n "$available_cc" ]; then
        info "可用算法: ${GREEN}${available_cc}${NC}"
    fi
    
    # Check SQM
    if opkg list-installed 2>/dev/null | grep -q "sqm-scripts"; then
        info "SQM 状态: ${GREEN}已安装${NC}"
    else
        info "SQM 状态: ${YELLOW}未安装${NC}"
    fi
    
    # Check config files
    if [ -f /etc/sysctl.d/12-tcp-bbr.conf ]; then
        info "BBR 配置: ${GREEN}已配置${NC} ✓"
    else
        info "BBR 配置: ${YELLOW}未配置${NC}"
    fi
    
    echo ""
}

# View current configuration
view_config() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║${NC}          ${GREEN}当前 TCP 配置${NC}                 ${BLUE}║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
    
    echo ""
    echo -e "${GREEN}[拥塞控制]${NC}"
    echo "tcp_congestion_control = $(cat /proc/sys/net/ipv4/tcp_congestion_control 2>/dev/null || echo '未知')"
    echo "default_qdisc = $(cat /proc/sys/net/core/default_qdisc 2>/dev/null || echo '未知')"
    echo "available = $(cat /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null || echo '未知')"
    
    echo ""
    echo -e "${GREEN}[网络缓冲区]${NC}"
    echo "rmem_max = $(cat /proc/sys/net/core/rmem_max 2>/dev/null || echo '未知')"
    echo "wmem_max = $(cat /proc/sys/net/core/wmem_max 2>/dev/null || echo '未知')"
    echo "tcp_rmem = $(cat /proc/sys/net/ipv4/tcp_rmem 2>/dev/null || echo '未知')"
    echo "tcp_wmem = $(cat /proc/sys/net/ipv4/tcp_wmem 2>/dev/null || echo '未知')"
    
    echo ""
    echo -e "${GREEN}[TCP 参数]${NC}"
    echo "tcp_fastopen = $(cat /proc/sys/net/ipv4/tcp_fastopen 2>/dev/null || echo '未知')"
    echo "tcp_syncookies = $(cat /proc/sys/net/ipv4/tcp_syncookies 2>/dev/null || echo '未知')"
    echo "tcp_tw_reuse = $(cat /proc/sys/net/ipv4/tcp_tw_reuse 2>/dev/null || echo '未知')"
    
    echo ""
    echo -e "${GREEN}[配置文件]${NC}"
    if [ -f /etc/sysctl.d/12-tcp-bbr.conf ]; then
        echo "BBR 配置文件内容:"
        echo "----------------------------------------"
        cat /etc/sysctl.d/12-tcp-bbr.conf
        echo "----------------------------------------"
    else
        echo "BBR 配置文件不存在"
    fi
    
    echo ""
    echo -e "${GREEN}[加载的模块]${NC}"
    lsmod 2>/dev/null | grep -E "bbr|fq" || echo "未加载相关模块"
    
    echo ""
}

# Install required packages
install_packages() {
    info "正在检查并安装必要的软件包..."
    
    echo ""
    echo "将安装以下软件包:"
    echo "  - kmod-tcp-bbr (BBR 拥塞控制模块)"
    echo "  - kmod-sched-fq (FQ 队列调度器)"
    echo ""
    
    printf "是否继续? [Y/n]: "
    read -r choice
    case "$choice" in
        n|N)
            info "已取消"
            return 1
            ;;
    esac
    
    info "更新软件包列表..."
    opkg update
    
    info "安装 kmod-tcp-bbr..."
    opkg install kmod-tcp-bbr
    
    info "安装 kmod-sched-fq..."
    opkg install kmod-sched-fq
    
    # Optional: Install SQM
    echo ""
    printf "是否安装 SQM (智能队列管理)? [y/N]: "
    read -r sqm_choice
    case "$sqm_choice" in
        y|Y)
            info "安装 SQM..."
            opkg install luci-app-sqm sqm-scripts
            success "SQM 已安装，请在 LuCI 界面配置"
            ;;
    esac
    
    success "软件包安装完成！"
}

# Quick setup
quick_setup() {
    info "正在执行一键优化配置..."
    echo ""
    
    # Check and install BBR package
    if ! check_bbr_package; then
        warning "需要先安装 BBR 模块包"
        if ! install_bbr_package; then
            error "安装失败，请检查网络连接和软件源"
            return 1
        fi
    fi
    
    # Enable BBR optimized
    enable_bbr_optimized
    
    echo ""
    success "一键优化完成！"
    warning "建议重启路由器以确保所有配置生效"
}

# Reboot prompt
prompt_reboot() {
    echo ""
    printf "是否现在重启路由器? [y/N]: "
    read -r choice
    case "$choice" in
        y|Y)
            info "路由器重启中..."
            reboot
            ;;
        *)
            info "请稍后手动重启路由器"
            ;;
    esac
}

# Main menu
show_menu() {
    clear
    check_status
    
    echo -e "
${GREEN_BG} OpenWrt TCP 加速管理脚本 ${NC} ${GREEN}[v${sh_ver}]${NC}
${GREEN}适用于 OpenWrt 19.07+${NC}

${BLUE}━━━━━━━━━━━━ BBR 加速管理 ━━━━━━━━━━━━${NC}
 ${GREEN}1.${NC} 启用 BBR 加速
 ${GREEN}2.${NC} 启用 BBR 加速 (优化版)
 ${GREEN}3.${NC} 禁用 BBR 加速

${BLUE}━━━━━━━━━━━━ 系统管理 ━━━━━━━━━━━━━━━━${NC}
 ${GREEN}4.${NC} 安装必要软件包
 ${GREEN}5.${NC} 查看当前配置
 ${GREEN}6.${NC} SQM 安装说明

${BLUE}━━━━━━━━━━━━ 快捷操作 ━━━━━━━━━━━━━━━━${NC}
 ${GREEN}7.${NC} 一键优化
 ${GREEN}8.${NC} 重启路由器

${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}
 ${GREEN}0.${NC} 退出脚本
${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}
"
    
    printf "请输入数字 [0-8]: "
    read -r choice
    case "$choice" in
        1)
            enable_bbr
            ;;
        2)
            enable_bbr_optimized
            ;;
        3)
            remove_all
            ;;
        4)
            install_packages
            ;;
        5)
            view_config
            ;;
        6)
            enable_sqm_info
            ;;
        7)
            quick_setup
            ;;
        8)
            prompt_reboot
            ;;
        0)
            info "退出脚本"
            exit 0
            ;;
        *)
            error "请输入正确的数字 [0-8]"
            sleep 2
            ;;
    esac
    
    # Return to menu
    echo ""
    printf "按回车键返回主菜单..."
    read -r _
    show_menu
}

# Command line arguments
handle_args() {
    case "$1" in
        --enable|-e)
            check_root
            check_openwrt
            enable_bbr
            ;;
        --enable-optimized|-o)
            check_root
            check_openwrt
            enable_bbr_optimized
            ;;
        --disable|-d)
            check_root
            check_openwrt
            remove_all
            ;;
        --status|-s)
            check_openwrt
            check_status
            ;;
        --help|-h)
            echo "OpenWrt TCP 加速脚本 v${sh_ver}"
            echo ""
            echo "用法: $0 [选项]"
            echo ""
            echo "选项:"
            echo "  --enable, -e          启用 BBR"
            echo "  --enable-optimized, -o 启用 BBR (优化版)"
            echo "  --disable, -d         禁用 BBR"
            echo "  --status, -s          查看状态"
            echo "  --help, -h            显示帮助"
            echo ""
            echo "不带参数运行将进入交互式菜单"
            ;;
        "")
            # No arguments, show menu
            check_root
            check_openwrt
            show_menu
            ;;
        *)
            error "未知选项: $1"
            echo "使用 --help 查看帮助"
            exit 1
            ;;
    esac
}

# Main execution
handle_args "$1"

